const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCSESS: 'USER_LOGIN_SUCSESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCSESS: 'FETCH_GENDER_SUCSESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCSESS: 'FETCH_POSITION_SUCSESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCSESS: 'FETCH_ROLE_SUCSESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCSESS: 'CREATE_USER_SUCSESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCSESS: 'EDIT_USER_SUCSESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCSESS: 'DELETE_USER_SUCSESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALL_USERS_SUCSESS: 'FETCH_ALL_USERS_SUCSESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_TOP_DOCTORS_SUCSESS: 'FETCH_TOP_DOCTORS_SUCSESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    FETCH_ALL_DOCTORS_SUCSESS: 'FETCH_ALL_DOCTORS_SUCSESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',


    SAVE_DETAIL_DOCTORS_SUCSESS: 'SAVE_DETAIL_DOCTORS_SUCSESS',
    SAVE_DETAIL_DOCTORS_FAILED: 'SAVE_DETAIL_DOCTORS_FAILED',


    FETCH_ALLCODE_SCHEDULE_TIME_SUCSESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCSESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',
})

export default actionTypes;